### ISSUE TITLE
Google Charts API scheduled to shut down

### ISSUE THREAD

**Issue by tejashah88** [ryanrolds/quiche#27]
According to the official Google Charts [documentation](https://developers.google.com/chart/image/), they plan to shut down the service by March 14, 2019, which would render half of the functionality of this library to be useless. What's the plan to handle this? Will we simply make a new major version removing all functionality related to that API?

**Comment by ryanrolds** [comment]
No plan for this. Please consider this project past EOL. I'm aware that some people created services that use the same query string API, but I'm not aware of any specific implementation.

**Comment by ryanrolds** [comment]
You can still use https://www.image-charts.com/. I would happily accept a PR that that service the default.

**Comment by tejashah88** [comment]
@ryanrolds Since this is technically a breaking change, should we release v1.0.0?
