### ISSUE TITLE
Is this module abandoned?

### ISSUE THREAD

**Issue by q2dg** [ryanrolds/quiche#3]
It's really useful, but it seems deprecated (in fact, https://code.google.com/apis/chart/image gives a suspicious 404 error). What a pitty.

**Comment by piranna** [comment]
[Google Image Charts](https://developers.google.com/chart/image/) API is deprecated in benefict on new, dynamic [Google Charts](https://developers.google.com/chart/) API, but old one is still working:

> **Deprecation notice**
> While the dynamic and interactive Google Charts are actively maintained, we officially deprecated the static Google Image Charts way back in 2012. This gives us the right to turn it off without notice, although we have no plans to do so.

I think this project could be still useful, but I think it could be a better option to create a new project that don't depend on external services and maybe based on [node-canvas](https://github.com/Automattic/node-canvas) (there's no one for Node.js!!! 8-O), maybe with an API based on the one from quiche.

**Comment by ryanrolds** [comment]
Looks like the URL changed. I can patch that up.

**Comment by piranna** [comment]
> Looks like the URL changed. I can patch that up.

:+1:

**Comment by ryanrolds** [comment]
Updated the URLs in the README. The library still works, but isn't being tested against 0.10 or 0.12. That has been rectified. Once travis comes back with OK builds I will push an update to npm.

**Comment by ryanrolds** [comment]
Bit late, but I did the publish.
