### ISSUE TITLE
Is there anyway we could add percentage to the chart

### ISSUE THREAD

**Issue by nicolelovecoding** [ryanrolds/quiche#5]
Hi, 

Thanks for providing this lib. By using it, I could generate nice beautifully 3D pie chart. 
However, it could be nicer if you could add the feature that show percentage besides the tag. Or if you already has this feature, let me know. Thanks!

**Comment by ryanrolds** [comment]
@OsamaYousry fixed this issue in his recent PR. An `addPercent()` function was added in 0.1.0.
