### ISSUE TITLE
normalize y axis

### ISSUE THREAD

**Issue by kerenfi** [ryanrolds/quiche#7]
hi I want to give my own parameters in y axis
and  put the data points accordinly,
but I get the y axis value authomaticlly from data points

(eq a  line graph that represent precentage values with max value 30% will have show 30% as the highest parameter in y axis and not 100 as expected)

Is there any solution for that?

**Comment by ryanrolds** [comment]
I will research this and get back to you.

**Comment by ryanrolds** [comment]
Sorry, this slipped through the cracks. I will look at this weekend and get back to you.

**Comment by ryanrolds** [comment]
Actually I'm wrong, I do see a range setting for the axis. I will add a function set the axis range. My other recommendation would work too.

**Comment by ryanrolds** [comment]
Added `setAxisRange(axis ["x", "r", "y"], start [number], end [number], step [number])` to line and bar charts. It should do what you need. The function will also set the data scale so that the labels and data match.

This is in version 0.3.0, which was just published.

**Comment by ryanrolds** [comment]
See https://github.com/ryanrolds/quiche/blob/master/test/line.range.test.js#L13
