### ISSUE TITLE
Google Image Chart deprecated 👎, Image-charts.com as a replacement 👍?

### ISSUE THREAD

**Issue by FGRibreau** [ryanrolds/quiche#8]
Hello @ryanrolds !

Awesome lib you did there! Since Google Image Chart could be shutdown at any time, we've built a **drop-in replacement** for it at image-charts.com. 

Would you be interested by a PR that adds support of Image-charts to Quiche? So users will be able to build their product on safe and futur-proof foundations?

**Comment by ryanrolds** [comment]
I would be happy to accept a PR that adds the ability to specify the server/service URI. Please make sure to include tests. If you have something else in mind please give me some details and we can discuss it.

**Comment by FGRibreau** [comment]
@ryanrolds done! Can't wait to read your feedbacks!
